# Generated by Django 3.2.18 on 2023-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='approval',
            field=models.IntegerField(choices=[(2, 'Aprovado'), (1, 'Pendente'), (0, 'Rejeitado')], default=1, max_length=1, verbose_name='Aprovação da Campanha'),
        ),
    ]
