# Generated by Django 3.2.18 on 2023-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='justify',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Justificativa campanha'),
        ),
    ]
